routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//
//Route::resource('products', 'ProductController');
//
//Route::resource('clients', 'ClientController');
//
//
Route::resource('requests', 'RequestController');
//
//Route::get('download/{id}', 'DownloadPDFController@download')->name("download");
Route::get('updateEmpty', 'RequestController@updateEmpty')->name("updateEmpty");
Route::get('charts', 'RequestController@charts')->name("charts");

Route::resource('parseJson', 'ParseJsonController');
Route::get('/', 'HomeController@index')->name("index");

app/Request.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Request extends Model
{
    protected $fillable = [
        'id',
        'url',
        'method',
        'retryCount',
        'resultsTotal',
        'hasNextPage',
        'durationSecs',
        'statusCode',
        'errorMessages',
    ];

    public $incrementing = false;

    protected $visible = [
        'id',
        'url',
        'method',
        'retryCount',
        'resultsTotal',
        'hasNextPage',
        'durationSecs',
        'statusCode',
        'errorMessages',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    protected $primaryKey = 'id';
}

app/Http/Controllers/RequestController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Result;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use DateTime;
use Illuminate\Support\Facades\Date;

class RequestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['title'] = "Requests";
        $data['requests'] = DB::table('requests')
            ->orderBy('created_at','desc')
            ->paginate(10);
        return view("requests.index ",$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    public function updateEmpty() {
        $data['title'] = "Requests";
        $data['result'] = DB::table('results')
            ->orderBy('created_at','desc')
            ->where("companyName","=","")
            ->first();
        $data['count'] = DB::table('results')
            ->orderBy('created_at','desc')
            ->where("companyName","=","")
            ->count();
        return view("results.edit ",$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    public function charts() {
        $data['title'] = 'Charts';

        $data['test'] = DB::table('results')
            ->join('requests', 'requests.id', '=', 'results.requestID')
                ->join('search_queries', 'results.requestID', '=', 'search_queries.requestID')
            ->select("companyName", DB::raw('COUNT(results.id) as count')
                ,DB::raw("DATE_FORMAT(date, '%Y%m') as yearmonth"),DB::raw('search_queries.term as term'))
            ->groupBy("companyName",
                DB::raw("DATE_FORMAT(date, '%Y%m')"),"search_queries.term")
            ->orderBy("date","asc")
            ->get();
        $finaleArray = array();
        $x = 0;
        $typeofQueries = DB::table( 'search_queries')->select('term')->distinct()->get();
            foreach($typeofQueries as $query) {
                $newArray = array();
                foreach($data['test'] as $record) {
                    if (strcmp($record->term,$query->term) == 0) {
                        if (isset($record->yearmonth)) {
                            $date = Carbon::createFromDate(substr($record->yearmonth,0,4),
                                    substr($record->yearmonth,4,6), 1)->getTimestamp()*1000;
                            array_push($newArray,array("x" => $date,"title"=>$record->term,
                                "y" => $record->count,"label" => $record->companyName ? $record->companyName : "nil"));
                        }
                    }
                }
                $x += 1;
                $we["title"]= $query->term;
                $we["array"] = array($newArray);
                array_push($finaleArray,$we);
            }
            $data['test'] = $typeofQueries;
        $data["dataPoints"] = $finaleArray;
        return view("charts.index",$data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Result::where('id',$id)->update(
            [
                "companyName"=> $request->companyName,
            ]
        );

        $data['title'] = "Requests";
        $data['result'] = DB::table('results')
            ->orderBy('created_at','desc')
            ->where("companyName","=","")
            ->first();
        $data['count'] = DB::table('results')
            ->orderBy('created_at','desc')
            ->where("companyName","=","")
            ->count();

        return view("results.edit ",$data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Request::where('id',$id)->delete();
        //Request::where('requestID', $id)->delete();

        return Redirect::to('requests')->with('success','Requests deleted successfully');
    }

}

resources/views/Requests/index.blade.php
@extends('layouts.default')

<div>
    @include('requests.table');
</div>

resources/views/Requests/table.blade.php
@section('content')

<div class="buttonRow">
    <a href="" class="btn btn-success mb-2">Add</a>
</div>

<div class="">
    <table class="table table-bordered" id="laravel_crud">
        <thead>
        <tr>
            <th>Id</th>
            <th>URL</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th colspan="1" class="text-center">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($requests as $request)
        <tr>
            <td>{{ $request->id }}</td>
            <td>{{ $request->url }}</td>
            <td>{{ $request->created_at }}</td>
            <td>{{ $request->updated_at }}</td>
            <td class="">
                <div>
                    <a href="{{ route('requests.edit',$request->id)}}" style="display:inline-block" class="btn btn-primary">Edit</a>
                    <form action="{{ route('requests.destroy', $request->id)}}" style="display:inline-block"  method="post">
                        {{ csrf_field() }}
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </div>
            </td>
        </tr>
        @endforeach

        @if(count($requests) < 1)
        <tr>
            <td colspan="10" class="text-center">There are no request available yet!</td>
            </td>
        </tr>
        @endif
        </tbody>
    </table>
    <div style="display:flex;justify-content:center">
        {{$requests->links()}}
    </div>
</div>
@endsection