routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//
//Route::resource('products', 'ProductController');
//
//Route::resource('clients', 'ClientController');
//
//
Route::resource('requests', 'RequestController');
//
//Route::get('download/{id}', 'DownloadPDFController@download')->name("download");
Route::get('updateEmpty', 'RequestController@updateEmpty')->name("updateEmpty");
Route::get('charts', 'RequestController@charts')->name("charts");

Route::resource('parseJson', 'ParseJsonController');
Route::get('/', 'HomeController@index')->name("index");

resources/views/Layouts/default.blade.php
@extends('app')

<!doctype html>
<html>
<head>
    @include('layouts.navbar')
</head>
<body>
<div class="container">

    <header>
    <h2>{{ $title }}</h2>
    </header>

    <div id="main">
    @if(session()->has('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
    @endif
         @yield('content')
    </div>

    <footer class="row">
    </footer>

</div>
</body>
</html>

resources/views/Layouts/navbar.blade.php
<div>
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">LyteJP</a>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                   <a href="/#" class="nav-link">
                       Home
                   </a>
                </li>
                <li class="nav-item">
                   <a href="{{ route('parseJson.index') }}" class="nav-link">
                       Parse Json
                   </a>
                </li>
                <li class="nav-item">
                   <a href="{{ route('requests.index') }} " class="nav-link">
                       View data
                   </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('updateEmpty') }} " class="nav-link">
                        Update company's name
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('charts') }} " class="nav-link">
                        Charts
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
</div>