routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//
//Route::resource('products', 'ProductController');
//
//Route::resource('clients', 'ClientController');
//
//
Route::resource('requests', 'RequestController');
//
//Route::get('download/{id}', 'DownloadPDFController@download')->name("download");
Route::get('updateEmpty', 'RequestController@updateEmpty')->name("updateEmpty");
Route::get('charts', 'RequestController@charts')->name("charts");

Route::resource('parseJson', 'ParseJsonController');
Route::get('/', 'HomeController@index')->name("index");

app/Result.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
    protected $fillable = [
        'title',
        'displayURL',
        'description',
        'companyName',
        'date',
        'requestID',
    ];

    public $incrementing = true;

    protected $visible = [
        'id',
        'title',
        'displayURL',
        'description',
        'companyName',
        'date',
        'requestID',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    protected $primaryKey = 'id';
}

app/Http/Controllers/ResultController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ResultController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Results/edit.blade.php
@extends('layouts.default')

@section('content')
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.css" rel="stylesheet">

<div class="buttonRow">
    <div>
        {{ $count }} left.
    </div>
    <div class="text-right">
        <a href="{{ route('requests.index') }}" class="btn btn-danger mb-2">Go Back</a>
    </div>
</div>
<hr />
@if(!empty($result->id))
<form action="{{ route('requests.update', $result->id) }}" method="POST" name="update_result">
    @method('PATCH')
    {{ csrf_field() }}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <strong>Title</strong>
                    <textarea rows="10"type="text" id="descriptionBox" name="title" readonly="readonly" class="form-control">{{$result->title}}
                    </textarea>
                </div>
                <div class="form-group">
                    <strong>Description</strong>
                    <textarea rows="10"type="text" id="descriptionBox" name="descriptionBox" readonly="readonly" class="form-control">{{$result->description}}
                    </textarea>
                </div>
                <div class="form-group">
                    <strong>Company Name</strong>
                    <input type="text" id="companyName" class="form-control" name="companyName" placeholder="Enter Company Name:">
                    <span class="text-danger">{{ $errors->first('invoiceDate') }}</span>
                </div>
        <div class="row">
            <div class="col-md-12">
                <button type="button" id="buttonActivate" class="btn btn-primary">Highlighted Text</button>
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{ route('requests.index') }}" class="btn btn-danger">Cancel</a>
            </div>
        </div>
</form>
@endif
@endsection